# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
    config.vm.box = "geerlingguy/centos8"
  
    config.ssh.insert_key = false
  
    config.vm.synced_folder ".", "/vagrant", disabled:true

    config.vm.provider :virtualbox do |v|
      v.memory = 10192
      v.linked_clone = true
      v.cpus = 8
    end
    
    #App server 1
    config.vm.define "bamboo-spec" do |app|
      app.vm.hostname = "orc-app.test"
      app.vm.network :private_network, ip: "192.168.60.4"
    end

    if Vagrant.has_plugin?("vagrant-timezone")
      config.timezone.value = "America/Santiago"
   end
end