# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled:true

  config.vm.provider :vmware_fusion do |v|
    v.memory = 256
    v.linked_clone = true
  end

  #App server 1
  config.vm.define "app1" do |app|
    app.vm.hostname = "orc-app1.test"
  end

  #App server 2
  config.vm.define "app2" do |app|
    app.vm.hostname = "orc-app2.test"
  end

  #DB Server
  config.vm.define "db" do |db|
    db.vm.hostname = "orc-db.test"
  end
end
