---
- name: Mi playbook
  hosts: localhost
  remote_user: root
  tasks:
     - name: Ensure apache is at the latest version
       ansible.builtin.yum:
         name: maven
         state: latest
     - name: Instalar tools
       yum:
        name:
         - nginx
         - wget
         - nano
         - git
       state: latest
       update_cache: true
