---
- name: Mi playbook
  hosts: localhost
  remote_user: root
  tasks:
     - name: Ensure apache is at the latest version
       ansible.builtin.yum:
         name: maven
         state: latest
     - name: Instalar listado de apps
       ansible.builtin.yum:
        - nginx
        - postgresql
        - postgresql-server
       state: present
