---
- name: Mi playbook
  hosts: localhost
  remote_user: root
  
  tasks:
  - name: ensure wget is installed
    ansible.builtin.yum:
      name: wget
      state: present
      update_cache: true
    become: true
  - name: ensure maven is installed
    yum:
      name: maven
      state: present
      update_cache: true
    become: true
